/**
 * Loadout Profile Mock Data - Step 15 Corrected
 * 11 profiles for AI workstation GPU allocation
 */

export const PROFILES_MOCK = [
  {
    name: 'inference-small',
    description: 'Light inference, 7B–13B models (GPU 0+3)',
    gpus: [0, 3],
    nvlink_pairs: [[0, 3]],
    services: ['ollama'],
    vram_required_gb: 16,
    use_case: '7B–13B via Ollama',
    accent: 'cyan',
    exclusive: false,
    incompatible_with: [
      'inference-pair-a', 'inference-4gpu', 'inference-4gpu-large',
      'dual-stack', 'training-lora-text', 'training-unsloth',
    ],
  },
  {
    name: 'inference-pair-a',
    description: 'Tensor-parallel 32B–40B models (NVLink A)',
    gpus: [0, 3],
    nvlink_pairs: [[0, 3]],
    services: ['vllm-pair-a', 'ollama'],
    vram_required_gb: 48,
    use_case: '32B–40B fast inference (NVLink A)',
    accent: 'cyan',
    exclusive: false,
    incompatible_with: [
      'inference-small', 'inference-4gpu', 'inference-4gpu-large',
      'dual-stack', 'training-lora-text', 'training-lora-image', 'training-unsloth',
    ],
  },
  {
    name: 'inference-pair-b',
    description: 'Tensor-parallel 32B–40B models (NVLink B)',
    gpus: [1, 2],
    nvlink_pairs: [[1, 2]],
    services: ['vllm-pair-b'],
    vram_required_gb: 48,
    use_case: '32B–40B fast inference (NVLink B)',
    accent: 'cyan',
    exclusive: false,
    incompatible_with: [
      'inference-4gpu', 'inference-4gpu-large', 'dual-stack',
      'training-lora-text', 'training-lora-image', 'image-studio',
    ],
  },
  {
    name: 'inference-4gpu',
    description: 'Full tensor-parallel 70B+ models (all GPUs, TP=4)',
    gpus: [0, 1, 2, 3],
    nvlink_pairs: [[0, 3], [1, 2]],
    services: ['vllm-4gpu'],
    vram_required_gb: 88,
    use_case: '70B+ full precision (TP=4)',
    accent: 'cyan',
    exclusive: false,
    incompatible_with: [
      'inference-pair-a', 'inference-pair-b', 'inference-small', 'inference-4gpu-large',
      'dual-stack', 'training-lora-text', 'training-lora-image', 'training-unsloth', 'image-studio',
    ],
  },
  {
    name: 'inference-4gpu-large',
    description: 'Pipeline-parallel 130B+ models (all GPUs, TP=2 PP=2)',
    gpus: [0, 1, 2, 3],
    nvlink_pairs: [[0, 3], [1, 2]],
    services: ['vllm-4gpu'],
    vram_required_gb: 96,
    use_case: '130B+ pipeline-parallel — exclusive',
    accent: 'cyan',
    exclusive: true,
    incompatible_with: [
      'inference-pair-a', 'inference-pair-b', 'inference-small', 'inference-4gpu',
      'dual-stack', 'training-lora-text', 'training-lora-image', 'training-unsloth', 'image-studio',
    ],
  },
  {
    name: 'dual-stack',
    description: 'Two simultaneous 32B models (NVLink A + B)',
    gpus: [0, 1, 2, 3],
    nvlink_pairs: [[0, 3], [1, 2]],
    services: ['vllm-pair-a', 'vllm-pair-b'],
    vram_required_gb: 96,
    use_case: 'Two simultaneous 32B inference endpoints',
    accent: 'cyan',
    exclusive: true,
    incompatible_with: [
      'inference-pair-a', 'inference-pair-b', 'inference-small',
      'inference-4gpu', 'inference-4gpu-large',
      'training-lora-text', 'training-lora-image', 'training-unsloth', 'image-studio',
    ],
  },
  {
    name: 'image-studio',
    description: 'Image generation + text inference (GPU 0 + pair B)',
    gpus: [0, 1, 2],
    nvlink_pairs: [[1, 2]],
    services: ['comfyui', 'real-esrgan', 'rembg', 'vllm-pair-b'],
    vram_required_gb: 72,
    use_case: 'SDXL/FLUX image gen + 32B text inference',
    accent: 'purple',
    exclusive: false,
    incompatible_with: [
      'inference-pair-b', 'inference-4gpu', 'inference-4gpu-large',
      'dual-stack', 'training-lora-text', 'training-lora-image',
    ],
  },
  {
    name: 'training-lora-image',
    description: 'Image LoRA fine-tuning via Kohya_ss (GPU 1+2)',
    gpus: [1, 2],
    nvlink_pairs: [[1, 2]],
    services: ['kohya', 'label-studio'],
    vram_required_gb: 48,
    use_case: 'Stable Diffusion LoRA / DreamBooth',
    accent: 'amber',
    exclusive: false,
    incompatible_with: [
      'inference-pair-b', 'inference-4gpu', 'inference-4gpu-large',
      'dual-stack', 'training-lora-text', 'training-unsloth',
    ],
  },
  {
    name: 'training-lora-text',
    description: 'Text fine-tuning via Axolotl FSDP (all GPUs)',
    gpus: [0, 1, 2, 3],
    nvlink_pairs: [[0, 3], [1, 2]],
    services: ['axolotl'],
    vram_required_gb: 90,
    use_case: 'Full text fine-tune FSDP — exclusive',
    accent: 'amber',
    exclusive: true,
    incompatible_with: [
      'inference-pair-a', 'inference-pair-b', 'inference-small',
      'inference-4gpu', 'inference-4gpu-large', 'dual-stack',
      'training-lora-image', 'training-unsloth', 'image-studio',
    ],
  },
  {
    name: 'training-unsloth',
    description: 'Fast LoRA fine-tuning via Unsloth (GPU 0+3)',
    gpus: [0, 3],
    nvlink_pairs: [[0, 3]],
    services: ['unsloth'],
    vram_required_gb: 48,
    use_case: 'Fast LoRA fine-tuning (NVLink A)',
    accent: 'amber',
    exclusive: false,
    incompatible_with: [
      'inference-pair-a', 'inference-small', 'inference-4gpu',
      'inference-4gpu-large', 'dual-stack',
      'training-lora-text', 'training-lora-image',
    ],
  },
  {
    name: 'idle',
    description: 'No GPU allocation — CPU-only services',
    gpus: [],
    nvlink_pairs: [],
    services: [],
    vram_required_gb: 0,
    use_case: 'Maintenance, scheduling, browse chat history',
    accent: 'gray',
    exclusive: false,
    incompatible_with: [],
  },
];
